inherit_from: ~/.rubocop.yml

Layout/CommentIndentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: [key, table]
  EnforcedColonStyle: [key, table]

Layout/IndentationWidth:
  Width: 1 # 1 Tab. I will surely not use spaces.

Layout/LineLength:
  Max: 340

Layout/Tab:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength: # WTF?!
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength: # Method length?! What the heck?
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false # Has no option to allow camel case.

Naming/VariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false # I know how to use class variables...

Style/CommentedKeyword:
  Enabled: false

Style/For:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfInsideElse:
 AllowIfModifier: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/ParallelAssignment: # But of course I will use that!
  Enabled: false

Style/ParenthesesAroundCondition: # Sorry, too used to C style ;)
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
