include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
#- typecheck
- require_not_found
- update_errors
require_paths: []
max_files: 5000
